SUPABASE_URL = "https://supabase.com/dashboard/project/dqxeufjvanoywztldlht"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxeGV1Zmp2YW5veXd6dGxkbGh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYzNTY5MzIsImV4cCI6MjEwMTkzMjkzMn0.9z7sJGO9tsN51qwcSlY_3yhJ-q_eLnUvunAnFDH8sLw"
HF_TOKEN = "your-huggingface-token-if-using-ai"
